export const TOP_500_ARTISTS = [
  // Hip-Hop & Rap
  "Drake", "Kendrick Lamar", "J. Cole", "Travis Scott", "Future",
  "Lil Baby", "Gunna", "21 Savage", "Lil Uzi Vert", "Playboi Carti",
  "Tyler, the Creator", "Chance the Rapper", "Mac Miller", "Post Malone",
  "Juice WRLD", "Polo G", "Rod Wave", "Jack Harlow", "Lil Durk",
  "NBA YoungBoy", "Moneybagg Yo", "42 Dugg", "EST Gee", "Mozzy",
  "Blxst", "Bino Rideaux", "Vince Staples", "Freddie Gibbs", "Boldy James",
  "Westside Gunn", "Conway the Machine", "Benny the Butcher", "Pusha T",
  "Jay-Z", "Kanye West", "Nas", "Eminem", "Lil Wayne", "Rick Ross",
  "Meek Mill", "2Pac", "The Notorious B.I.G.", "Wu-Tang Clan", "Rakim",
  "Big L", "Big Pun", "DMX", "Ludacris", "T.I.", "Jeezy",
  "Gucci Mane", "Waka Flocka Flame", "Soulja Boy", "Lil Jon", "Nelly",
  "Outkast", "Goodie Mob", "Killer Mike", "Run The Jewels", "Big K.R.I.T.",
  "Childish Gambino", "Kid Cudi", "Wale", "Big Sean", "Wiz Khalifa",
  "Curren$y", "Logic", "G-Eazy", "Tech N9ne", "Lil Pump",
  "Trippie Redd", "XXXTentacion", "Ski Mask the Slump God", "Kodak Black",
  "Latto", "Flo Milli", "GloRilla", "Ice Spice", "Doechii", "Sexyy Red",
  "Coi Leray", "Lakeyah", "BIA", "Rapsody", "Noname", "Tierra Whack",
  "JPEGMafia", "Danny Brown", "BROCKHAMPTON", "Earthgang", "JID",
  "Dreamville", "Bas", "Ari Lennox", "Cozz", "Lute",
  "50 Cent", "Lloyd Banks", "Tony Yayo", "The Game", "Ice Cube",
  "Snoop Dogg", "Dr. Dre", "Xzibit", "Warren G", "Nate Dogg",
  "Method Man", "Redman", "Ghostface Killah", "Raekwon", "GZA",
  "RZA", "Ol' Dirty Bastard", "Common", "Mos Def", "Talib Kweli",
  "Black Thought", "Q-Tip", "A Tribe Called Quest", "De La Soul",
  "Pharcyde", "Digable Planets", "Hieroglyphics", "Del the Funky Homosapien",

  // R&B & Soul
  "SZA", "Beyoncé", "Rihanna", "The Weeknd", "Frank Ocean",
  "Brent Faiyaz", "Lucky Daye", "6LACK", "Daniel Caesar", "Miguel",
  "H.E.R.", "Jazmine Sullivan", "Summer Walker", "Jhené Aiko",
  "Kehlani", "Tinashe", "Ella Mai", "Victoria Monét", "Bryson Tiller",
  "Giveon", "Ant Clemons", "Snoh Aalegra", "Yebba", "Pink Sweat$",
  "Masego", "Tom Misch", "Jordan Ward", "PJ Morton", "BJ The Chicago Kid",
  "Eric Bellinger", "Marsha Ambrosius", "Lalah Hathaway", "Ledisi",
  "Fantasia", "Jennifer Hudson", "Kelly Rowland", "Michelle Williams",
  "Ciara", "Ashanti", "Monica", "Brandy", "Mary J. Blige",
  "Alicia Keys", "John Legend", "Usher", "Ne-Yo", "Chris Brown",
  "Trey Songz", "Tank", "Tyrese", "Ginuwine", "Joe",
  "Jaheim", "R. Kelly", "Jodeci", "Boyz II Men", "New Edition",
  "Keith Sweat", "Babyface", "Teddy Riley", "Guy", "Bell Biv DeVoe",
  "Janet Jackson", "Michael Jackson", "Prince", "Stevie Wonder",
  "Marvin Gaye", "Aretha Franklin", "Otis Redding", "Sam Cooke",
  "Curtis Mayfield", "Al Green", "Bill Withers", "Luther Vandross",
  "Anita Baker", "Sade", "Erykah Badu", "D'Angelo", "Maxwell",
  "Jill Scott", "India.Arie", "Anthony Hamilton", "Raphael Saadiq",
  "Anthony Hamilton", "Musiq Soulchild", "Dwele", "Bilal",

  // Pop
  "Taylor Swift", "Ariana Grande", "Billie Eilish", "Olivia Rodrigo",
  "Dua Lipa", "Harry Styles", "Shawn Mendes", "Camila Cabello",
  "Selena Gomez", "Justin Bieber", "Ed Sheeran", "Bruno Mars",
  "Katy Perry", "Lady Gaga", "Pink", "Kesha", "Miley Cyrus",
  "Halsey", "Bebe Rexha", "Meghan Trainor", "Charlie Puth",
  "Jason Derulo", "Troye Sivan", "Conan Gray", "Gracie Abrams",
  "Sabrina Carpenter", "Chappell Roan", "Charli XCX", "Lorde",
  "Lana Del Rey", "Phoebe Bridgers", "Maggie Rogers", "Hozier",
  "Justin Timberlake", "NSYNC", "Backstreet Boys", "Christina Aguilera",
  "Britney Spears", "Nelly Furtado", "Gwen Stefani", "No Doubt",
  "Paramore", "Hayley Williams", "Fall Out Boy", "Panic! at the Disco",
  "My Chemical Romance", "Gym Class Heroes", "Cobra Starship",
  "OneRepublic", "Maroon 5", "Train", "Matchbox Twenty",
  "Imagine Dragons", "Twenty One Pilots", "Bastille", "Coldplay",
  "Demi Lovato", "Jordin Sparks", "Kelly Clarkson", "Carrie Underwood",
  "FINNEAS", "Khalid", "Ali Gatie", "Jeremy Zucker", "chelsea cutler",
  "Role Model", "Stephen Sanchez", "Tate McRae", "Jvke", "Surfaces",

  // Rock & Alternative
  "Foo Fighters", "Red Hot Chili Peppers", "Green Day", "The Killers",
  "Arctic Monkeys", "Radiohead", "Nirvana", "Pearl Jam", "Soundgarden",
  "Alice in Chains", "Stone Temple Pilots", "Weezer", "Beck",
  "The Strokes", "Interpol", "Franz Ferdinand", "Kings of Leon",
  "Jack White", "The White Stripes", "The Black Keys", "Gary Clark Jr.",
  "John Mayer", "Dave Matthews Band", "Phish", "Widespread Panic",
  "Grateful Dead", "Tom Petty", "Bruce Springsteen", "Bob Dylan",
  "Neil Young", "Fleetwood Mac", "Eagles", "Steely Dan", "Elton John",
  "Billy Joel", "Bon Jovi", "Aerosmith", "Guns N' Roses", "Metallica",
  "Tool", "Rage Against the Machine", "System of a Down", "Linkin Park",
  "Evanescence", "Slipknot", "Korn", "Deftones", "A Perfect Circle",
  "Queens of the Stone Age", "Muse", "Incubus", "Puddle of Mudd",
  "Nickelback", "Creed", "3 Doors Down", "Staind", "Breaking Benjamin",
  "Blink-182", "Sum 41", "Simple Plan", "Good Charlotte", "New Found Glory",
  "The Used", "Thursday", "Taking Back Sunday", "Brand New",
  "Dashboard Confessional", "Death Cab for Cutie", "The Postal Service",
  "Modest Mouse", "Built to Spill", "Bright Eyes", "Sufjan Stevens",
  "Iron & Wine", "Fleet Foxes", "Bon Iver", "The National",
  "Vampire Weekend", "MGMT", "Animal Collective", "Grizzly Bear",
  "Beach House", "Tame Impala", "Unknown Mortal Orchestra", "Mac DeMarco",
  "Alex G", "Snail Mail", "Mitski", "Soccer Mommy", "Japanese Breakfast",
  "Faye Webster", "Angel Olsen", "Big Thief", "Lucy Dacus",
  "Julien Baker", "boygenius", "Phoebe Bridgers", "Waxahatchee",
  "Sharon Van Etten", "Hand Habits", "Squirrel Flower",
  "Radiohead", "Portishead", "Massive Attack", "Tricky", "The XX",

  // Country & Americana
  "Morgan Wallen", "Luke Combs", "Zach Bryan", "Tyler Childers",
  "Chris Stapleton", "Kacey Musgraves", "Maren Morris", "Brandi Carlile",
  "Sturgill Simpson", "Jason Isbell", "Cody Jinks", "Willie Nelson",
  "Waylon Jennings", "Johnny Cash", "Dolly Parton", "Loretta Lynn",
  "Merle Haggard", "George Strait", "Alan Jackson", "Garth Brooks",
  "Tim McGraw", "Faith Hill", "Kenny Rogers", "Randy Travis",
  "Reba McEntire", "Shania Twain", "The Chicks", "Miranda Lambert",
  "Blake Shelton", "Luke Bryan", "Eric Church", "Dierks Bentley",
  "Keith Urban", "Brad Paisley", "Kenny Chesney", "Toby Keith",
  "Brooks & Dunn", "Rascal Flatts", "Lady A", "Sugarland",
  "Little Big Town", "Old Dominion", "Dan + Shay", "Sam Hunt",
  "Thomas Rhett", "Kane Brown", "Lainey Wilson", "Jelly Roll",
  "Hardy", "Bailey Zimmermann", "Nate Smith", "Jordan Davis",
  "Cody Johnson", "Turnpike Troubadours", "Whiskey Myers", "Blackberry Smoke",
  "Hank Williams", "Patsy Cline", "Emmylou Harris", "Gillian Welch",
  "David Rawlings", "Alison Krauss", "Union Station", "Old Crow Medicine Show",

  // Latin
  "Bad Bunny", "J Balvin", "Daddy Yankee", "Ozuna", "Maluma",
  "Nicky Jam", "Rauw Alejandro", "Anuel AA", "Karol G", "Becky G",
  "Anitta", "Shakira", "Enrique Iglesias", "Marc Anthony",
  "Jennifer Lopez", "Ricky Martin", "Pitbull", "Gloria Estefan",
  "Carlos Santana", "Los Lobos", "Celia Cruz", "Selena Quintanilla",
  "Peso Pluma", "Eslabon Armado", "Fuerza Regida", "Natanael Cano",
  "Bizarrap", "Myke Towers", "Jhay Cortez", "Sech", "Farruko",

  // Electronic & Dance
  "Marshmello", "Diplo", "Skrillex", "Calvin Harris", "The Chainsmokers",
  "Kygo", "Zedd", "Martin Garrix", "Tiësto", "David Guetta",
  "Porter Robinson", "Madeon", "Flume", "Disclosure", "Kaytranada",
  "Flying Lotus", "Thundercat", "Four Tet", "Jamie xx", "Caribou",
  "Bonobo", "Nicolas Jaar", "Floating Points", "Blood Orange",
  "Soulwax", "LCD Soundsystem", "Justice", "Daft Punk", "Gorillaz",
  "SBTRKT", "James Blake", "Mount Kimbie", "Jon Hopkins",
  "Fred Again..", "HAAi", "Peggy Gou", "Mall Grab",

  // Jazz & Neo-Soul
  "Kamasi Washington", "Robert Glasper", "Esperanza Spalding",
  "Snarky Puppy", "Norah Jones", "Diana Krall", "Gregory Porter",
  "Kurt Elling", "John Coltrane", "Miles Davis", "Thelonious Monk",
  "Charlie Parker", "Dizzy Gillespie", "Louis Armstrong",
  "Duke Ellington", "Billie Holiday", "Ella Fitzgerald",
  "Nina Simone", "Sarah Vaughan", "Chet Baker", "Dave Brubeck",
  "Wayne Shorter", "Herbie Hancock", "Chick Corea", "Pat Metheny",
  "Christian Scott", "Ambrose Akinmusire", "Kendrick Scott",
  "Terrace Martin", "James Fauntleroy",

  // Gospel & Christian
  "Kirk Franklin", "Tye Tribbett", "Travis Greene", "Maverick City Music",
  "Elevation Worship", "Hillsong UNITED", "Casting Crowns",
  "TobyMac", "Lauren Daigle", "Lecrae", "Andy Mineo", "Trip Lee",
  "KB", "Propaganda", "Sho Baraka",

  // Indie & Folk
  "Hozier", "Tom Misch", "Tom Odell", "Nick Drake", "Elliott Smith",
  "Cat Stevens", "Simon & Garfunkel", "Paul Simon", "James Taylor",
  "Carole King", "Joni Mitchell", "Joan Baez", "James Bay",
  "Dermot Kennedy", "Gregory Alan Isakov", "Joshua Radin",
  "Ray LaMontagne", "Damien Rice", "Glen Hansard",
  "Lord Huron", "The Head and the Heart", "Of Monsters and Men",
  "Mumford & Sons", "The Lumineers", "Edward Sharpe", "Florence + the Machine",
  "St. Vincent", "Feist", "Cat Power", "PJ Harvey",
  "Fiona Apple", "Neko Case", "Norah Jones", "Kathleen Edwards",
  "Allison Russell", "Amythyst Kiah", "Yola", "Brittany Howard",
  "Leon Bridges", "Gary Clark Jr.", "Alabama Shakes",

  // Afrobeats & Global
  "Burna Boy", "Wizkid", "Davido", "Tems", "Rema",
  "Fireboy DML", "Ckay", "Omah Lay", "Ayra Starr", "Asake",
  "Afrobeats to the World", "Tiwa Savage", "Yemi Alade",
  "Mr Eazi", "Wande Coal", "Olamide", "Phyno"
];
